{
 "title": "Containers",
 "description": "Containers metrics",
 "tags": [ "containers" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_cpu_user_seconds_total, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(container_cpu_user_seconds_total{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Host resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores on the host",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:9100\",job=~\"node-exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Host Total RAM",
   "type": "singlestat",
   "description": "Total RAM on the host",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:9100\",job=~\"node-exporter\"}"
    }
   ]
  },
  { "title": "Containers resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": " Containers Total CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Containers Total Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (name) (container_last_seen{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Running Containers Count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (count by (name) (container_last_seen{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}))",
     "legendFormat": "total containers count"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Usage - Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name,name) (irate(container_cpu_usage_seconds_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}[5m]) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage  - User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_user_seconds_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage - System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_system_seconds_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Memory Usage  - Total",
   "type": "graph",
   "description": "Current memory usage in bytes,   including all memory regardless of  when it was accessed",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage  - RSS",
   "type": "graph",
   "description": "Size of RSS in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage  - Cache",
   "type": "graph",
   "description": "Number of bytes of page cache memory",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_cache{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage  - Swap",
   "type": "graph",
   "description": "Container swap usage in bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_swap{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage  -  Failcnt",
   "type": "graph",
   "description": "Number of memory usage hits limits",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_failcnt{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Disk I/O Write ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name,device) (irate(container_fs_writes_bytes_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\",device!~\"/dev/md[0-9]\"}[5m]))",
     "legendFormat": "{{name}}  - {{device}} "
    }
   ]
  },
  {
   "title": "Disk I/O Read",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name,device) (irate(container_fs_reads_bytes_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\",device!~\"/dev/md[0-9]\"}[5m]))",
     "legendFormat": "{{name}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk IOps Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (name,device) (irate(container_fs_reads_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\",device!~\"/dev/md[0-9]\"}[5m]))",
     "legendFormat": "{{name}}  - {{device}} "
    }
   ]
  },
  {
   "title": "Disk IOps Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum by (name,device) (irate(container_fs_writes_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\",device!~\"/dev/md[0-9]\"}[5m]))",
     "legendFormat": "{{name}}  - {{device}} "
    }
   ]
  },
  { "title": "Network usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Input Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}[5m])",
     "legendFormat": "{{name}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Output Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}[5m])",
     "legendFormat": "{{name}} - {{ interface}}"
    }
   ]
  },
  {
   "title": "Input  Network Packets/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_packets_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}[5m])",
     "legendFormat": "{{name}} - {{ interface}}"
    }
   ]
  },
  {
   "title": "Output Network  Packets/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_packets_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}[5m])",
     "legendFormat": "{{name}} - {{ interface}}"
    }
   ]
  },
  {
   "title": "Input Network Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_errors_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}",
     "legendFormat": "{{name}} - {{ interface}}"
    }
   ]
  },
  {
   "title": "Output Network Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_network_transmit_errors_total{instance=~\"$node:$port\",job=~\"$job\",image!=\"\"}",
     "legendFormat": "{{name}} - {{ interface}}"
    }
   ]
  }
 ]
}