route:
  receiver: "slack"
  group_interval: 60s
  repeat_interval: 168h

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        title: '{{ template "custom_title" . }}'
        text: '{{ template "custom_slack_message" . }}'
templates:
  - /etc/alertmanager/notifications.tmpl

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["instance", "alertname"]
