global:
  slack_api_url: "${slack_api_url}"

route:
  receiver: "slack-notifications"

receivers:
  - name: "slack-notifications"
    slack_configs:
      - send_resolved: true
        channel: "${channel}"
        title: '{{ template "custom_title" . }}'
        text: '{{ template "custom_slack_message" . }}'

templates:
  - /etc/alertmanager/notifications.tmpl

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["instance", "alertname"]
